development:
  adapter: postgresql
  encoding: unicode
  database: reactrails_development
  pool: 5
  username: reactrails
  password: '123'

test:
  adapter: postgresql
  encoding: unicode
  database: reactrails
  pool: 5
  username: reactrails
  password: '123'